### ISSUE TITLE
Version 8.0

### ISSUE THREAD

**Issue by 10erNetzwerk** [YunoHost-Apps/rportd_ynh#5]
Hello,

I have seen that there is already an updated version in the repository of rport.io. How can I use this version (8.0)? 

https://github.com/cloudradar-monitoring/rport/releases/tag/0.8.0

**Comment by ericgaspar** [comment]
I am sure the maintainer wouldn't mind if you propose a PR with the update.

**Comment by tituspijean** [comment]
Hello, unfortunately the upstream app has been closed-sourced and its code repository deleted. No more development will be made on this package.
