### ISSUE TITLE
noVNC - Connection error

### ISSUE THREAD

**Issue by Optogram** [YunoHost-Apps/rportd_ynh#8]
Hello,

I tried to connect to my windows devices using VNC, with noVNC from the Browser. Everytime I get this error :

![Capture d’écran 2023-02-26 104433](https://user-images.githubusercontent.com/78688254/221403351-e7daad50-57c4-4797-a008-7bba02e8e5f7.jpg)

I tried the following instructions, but no luck : https://oss.rport.io/advanced/novnc-proxy/

`cd /tmp`
`curl -LO https://github.com/novnc/noVNC/archive/refs/tags/v1.3.0.zip`
`unzip -d /var/lib/rport v1.3.0.zip`
`rm -f v1.3.0.zip`

And after that, I can't manage to get to the `rportd.conf` to modify it.

Thanks for your time :)

**Comment by tituspijean** [comment]
Hello, unfortunately the upstream app has been closed-sourced and its code repository deleted. No more development will be made on this package.
